import type { Question } from "@/types";

export const MOCK_QUESTIONS: Question[] = [
  // --- Quantitative ---
  {
    id: "quant-1",
    section: "quant",
    topic: "ממוצעים",
    subtopic: "ממוצע משוקלל",
    difficulty: 3,
    type: "mcq",
    body: "בכיתה יש 30 תלמידים. ציון הבנים הממוצע הוא 80, וציון הבנות הממוצע הוא 90. אם הממוצע הכללי של הכיתה הוא 84, כמה בנות יש בכיתה?",
    passage: null,
    choices: ["10", "12", "15", "18"],
    correctAnswer: 1,
    explanation:
      "נשתמש בשיטת המרחקים לממוצע משוקלל: המרחק בין הממוצע הכללי לממוצע הבנות הוא $90 - 84 = 6$, והמרחק בין הממוצע הכללי לממוצע הבנים הוא $84 - 80 = 4$. היחס בין מספר הבנים למספר הבנות שווה ליחס ההפוך של המרחקים: $\\dfrac{\\text{בנים}}{\\text{בנות}} = \\dfrac{6}{4} = \\dfrac{3}{2}$. מחלקים את 30 התלמידים ל-5 חלקים שווים ($3+2$), כך שכל חלק שווה ל-6 תלמידים: $3 \\times 6 = 18$ בנים ו-$2 \\times 6 = 12$ בנות. בדיקה: $\\dfrac{18 \\times 80 + 12 \\times 90}{30} = \\dfrac{2520}{30} = 84$. טעות נפוצה היא להפוך את היחס ולחשב לפי המרחקים ישירות במקום ההפוך שלהם.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "quant-2",
    section: "quant",
    topic: "אלגברה",
    subtopic: "חזקות ושורשים",
    difficulty: 3,
    type: "mcq",
    body: "מהו הערך של $2^{3} \\cdot 2^{-1} \\cdot 4^{2}$?",
    passage: null,
    choices: ["$32$", "$64$", "$128$", "$16$"],
    correctAnswer: 1,
    explanation:
      "יש להעביר את כל הביטויים לבסיס משותף $2$: $4^2 = (2^2)^2 = 2^4$. כעת הביטוי הוא $2^{3} \\cdot 2^{-1} \\cdot 2^{4} = 2^{3-1+4} = 2^{6} = 64$. טעות נפוצה היא לחבר את החזקות בלי להמיר קודם את $4^2$ לבסיס $2$.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },

  {
    id: "quant-3",
    section: "quant",
    topic: "בעיות תנועה ועבודה",
    subtopic: "עבודה משותפת",
    difficulty: 3,
    type: "mcq",
    body: "פועל א' יכול לסיים עבודה מסוימת ב-6 שעות, ופועל ב' יכול לסיים את אותה עבודה ב-3 שעות. כמה זמן ייקח לשניהם יחד לסיים את העבודה, אם יעבדו בקצב קבוע לאורך כל הזמן?",
    passage: null,
    choices: ["$2$ שעות", "$1.5$ שעות", "$3$ שעות", "$4.5$ שעות"],
    correctAnswer: 0,
    explanation:
      "קצב העבודה של כל פועל הוא החלק מהעבודה שהוא מבצע בשעה אחת: פועל א' מבצע $\\dfrac{1}{6}$ מהעבודה בשעה, ופועל ב' מבצע $\\dfrac{1}{3}$ מהעבודה בשעה. הקצב המשותף הוא סכום הקצבים: $\\dfrac{1}{6} + \\dfrac{1}{3} = \\dfrac{1}{6} + \\dfrac{2}{6} = \\dfrac{3}{6} = \\dfrac{1}{2}$ מהעבודה בשעה. הזמן הנדרש הוא ההופכי של הקצב: $\\dfrac{1}{\\frac{1}{2}} = 2$ שעות. טעות נפוצה היא לחשב ממוצע פשוט של שני הזמנים ($4.5$ שעות) במקום לעבוד עם קצבים.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "quant-4",
    section: "quant",
    topic: "הסתברות וקומבינטוריקה",
    subtopic: "הסתברות בסיסית",
    difficulty: 2,
    type: "mcq",
    body: "בכיס יש 3 כדורים אדומים ו-2 כדורים כחולים, הזהים זה לזה במגע. שולפים כדור אחד באקראי. מה ההסתברות שהכדור שנשלף יהיה כחול?",
    passage: null,
    choices: ["$40\\%$", "$60\\%$", "$25\\%$", "$50\\%$"],
    correctAnswer: 0,
    explanation:
      "ההסתברות מחושבת כמספר התוצאות הרצויות חלקי מספר התוצאות האפשריות: יש 2 כדורים כחולים מתוך 5 כדורים בסך הכול, ולכן $P(\\text{כחול}) = \\dfrac{2}{5} = 0.4 = 40\\%$. טעות נפוצה היא לחשב את היחס ביחס למספר הכדורים האדומים ($\\dfrac{2}{3}$) במקום ביחס לסך כל הכדורים בכיס.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },

  // --- Verbal (Hebrew) ---
  {
    id: "verbal-1",
    section: "verbal",
    topic: "הבנה והבעה",
    subtopic: "השלמת משפטים",
    difficulty: 3,
    type: "mcq",
    body: "השלימו את המשפט: למרות שהמומחים __________ את התכנית, ראש העירייה החליט __________ אותה וליישם אותה כמות שהיא.",
    passage: null,
    choices: [
      "שיבחו / לדחות",
      "מתחו ביקורת על / לאמץ",
      "תמכו / לבטל",
      "התעלמו מ / לשנות",
    ],
    correctAnswer: 1,
    explanation:
      "המילה 'כמות שהיא' בסוף המשפט מרמזת שהתכנית יושמה ללא שינויים — כלומר הפועל השני חייב להיות עקבי עם 'אימוץ', ולא עם דחייה, ביטול או שינוי. מכיוון שיש ניגוד ('למרות ש'), הפועל הראשון חייב לבטא עמדה שלילית כלפי התכנית. רק התשובה 'מתחו ביקורת על / לאמץ' עומדת בשני התנאים.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "verbal-2",
    section: "verbal",
    topic: "חשיבה לוגית",
    subtopic: "היסק",
    difficulty: 3,
    type: "mcq",
    body: "בכיתה מסוימת, כל התלמידים שאוהבים מתמטיקה אוהבים גם פיזיקה. ידוע שדני לא אוהב פיזיקה. מה ניתן להסיק בוודאות?",
    passage: null,
    choices: ["דני אוהב מתמטיקה", "דני לא אוהב מתמטיקה", "דני אוהב פיזיקה", "לא ניתן להסיק דבר"],
    correctAnswer: 1,
    explanation:
      "הטענה 'כל מי שאוהב מתמטיקה אוהב גם פיזיקה' שקולה לוגית לטענה ההפוכה-נגדית: 'מי שלא אוהב פיזיקה, לא אוהב מתמטיקה'. מכיוון שדני לא אוהב פיזיקה, נובע בהכרח שדני לא אוהב מתמטיקה. זהו כלל יסוד בהיגיון (modus tollens) שחוזר הרבה בפרק ההיגיון.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },

  {
    id: "verbal-3",
    section: "verbal",
    topic: "הבנת הנקרא",
    subtopic: "הסקת מסקנות",
    difficulty: 3,
    type: "mcq_with_passage",
    passage:
      "מחקרים עדכניים מראים כי שינה איכותית משפרת את היכולת הקוגניטיבית ואת הזיכרון לטווח ארוך. עם זאת, מחסור כרוני בשינה עלול לגרום לירידה משמעותית ביכולת הריכוז ואף להשפיע לרעה על מצב הרוח. חוקרים ממליצים על 7-9 שעות שינה בלילה עבור מבוגרים, אך מציינים כי הצורך המדויק משתנה מאדם לאדם.",
    body: "מה ניתן להסיק מהקטע?",
    choices: [
      "כל אדם זקוק בדיוק ל-8 שעות שינה בלילה.",
      "מחסור בשינה עלול לפגוע הן ביכולת הריכוז והן במצב הרוח.",
      "שינה איכותית אינה קשורה לזיכרון לטווח ארוך.",
      "חוקרים ממליצים על פחות מ-7 שעות שינה למבוגרים.",
    ],
    correctAnswer: 1,
    explanation:
      "הקטע מציין במפורש שמחסור כרוני בשינה 'עלול לגרום לירידה משמעותית ביכולת הריכוז ואף להשפיע לרעה על מצב הרוח' — כלומר פוגע בשני התחומים גם יחד, ולכן תשובה ב' נכונה. תשובה א' שגויה כי הקטע מציין טווח (7-9 שעות) ולא מספר קבוע. תשובה ג' סותרת את הקטע, שקושר במפורש בין שינה איכותית לזיכרון. תשובה ד' הפוכה מהאמור בקטע.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "verbal-4",
    section: "verbal",
    topic: "חשיבה לוגית",
    subtopic: "קבוצות והיסק",
    difficulty: 3,
    type: "mcq",
    body: "כל הספרים בספרייה מסווגים לפי נושא. הספר 'קיץ' מסווג בקטגוריית 'ספרות יפה'. ידוע שאין אף ספר בקטגוריית 'ספרות יפה' שמסווג גם כ'ספר עיון'. מה ניתן להסיק בוודאות?",
    passage: null,
    choices: [
      "הספר 'קיץ' הוא ספר עיון.",
      "הספר 'קיץ' אינו ספר עיון.",
      "כל ספרי העיון הם ספרות יפה.",
      "לא ניתן להסיק דבר.",
    ],
    correctAnswer: 1,
    explanation:
      "הקטגוריות 'ספרות יפה' ו'ספר עיון' זרות זו לזו — אין ספר ששייך לשתיהן. מכיוון שהספר 'קיץ' מסווג כ'ספרות יפה', הוא אינו יכול להיות גם 'ספר עיון'. זהו היסק ישיר משתי הנחות על קבוצות זרות, ולכן תשובה ב' נובעת בוודאות.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },

  // --- English ---
  {
    id: "english-1",
    section: "english",
    topic: "Sentence Completion",
    subtopic: "Contrast Structures",
    difficulty: 3,
    type: "mcq",
    body: "Despite the committee's initial ______, they eventually approved the proposal after minor revisions.",
    passage: null,
    choices: ["enthusiasm", "reluctance", "certainty", "indifference"],
    correctAnswer: 1,
    explanation:
      "The word 'Despite' signals a contrast between the blank and the outcome ('eventually approved'). Only 'reluctance' creates a logical contrast — the committee was hesitant at first, but approved the proposal anyway. 'Enthusiasm' or 'certainty' would not require the word 'Despite', and 'indifference' does not logically lead to eventual approval.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "english-2",
    section: "english",
    topic: "Restatement",
    subtopic: "Meaning Preservation",
    difficulty: 3,
    type: "mcq",
    body: "Which of the following best restates the sentence: \"Although the results were disappointing, the research team remained optimistic about future experiments.\"",
    passage: null,
    choices: [
      "The research team's optimism about future experiments was unaffected by the disappointing results.",
      "The disappointing results made the research team pessimistic about future experiments.",
      "The research team was disappointed because future experiments seemed optimistic.",
      "Future experiments disappointed the research team despite their results.",
    ],
    correctAnswer: 0,
    explanation:
      "The original sentence states that despite disappointing results, the team stayed optimistic. Option A preserves this exact relationship. Option B reverses the meaning (pessimistic instead of optimistic). Options C and D scramble the logical relationship between the results and the team's outlook.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "english-3",
    section: "english",
    topic: "Reading Comprehension",
    subtopic: "Main Idea",
    difficulty: 3,
    type: "mcq_with_passage",
    passage:
      "Renewable energy sources, such as solar and wind power, have become increasingly cost-effective over the past decade. While initial installation costs remain a barrier for some communities, the long-term savings and environmental benefits continue to drive adoption worldwide. Experts predict that renewables could account for the majority of global electricity generation within the next twenty years.",
    body: "According to the passage, what is true about renewable energy adoption?",
    choices: [
      "Installation costs have made renewable energy economically unfeasible.",
      "Long-term savings and environmental benefits are encouraging wider adoption despite upfront costs.",
      "Renewables already account for the majority of global electricity generation.",
      "Experts believe renewable energy will never become dominant.",
    ],
    correctAnswer: 1,
    explanation:
      "The passage states that despite installation costs being a barrier, \"long-term savings and environmental benefits continue to drive adoption,\" matching option B exactly. Option A overstates the cost barrier as making adoption unfeasible. Option C confuses a future prediction (\"within the next twenty years\") with the present. Option D directly contradicts the experts' prediction described in the passage.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "english-4",
    section: "english",
    topic: "Sentence Completion",
    subtopic: "Cause and Effect",
    difficulty: 2,
    type: "mcq",
    body: "The evidence presented was so ______ that even the most skeptical jurors were persuaded of the defendant's innocence.",
    passage: null,
    choices: ["ambiguous", "compelling", "trivial", "circumstantial"],
    correctAnswer: 1,
    explanation:
      "The structure \"so ______ that even the most skeptical jurors were persuaded\" requires a word describing evidence strong enough to overcome skepticism. Only 'compelling' fits this cause-and-effect relationship. 'Ambiguous', 'trivial', and 'circumstantial' all describe weak or unclear evidence, which would not persuade skeptical jurors.",
    media: null,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
];
